version: '3.8'

services:
  # База данных для первого бота
  db1:
    image: postgres:15-alpine
    container_name: poster_db1
    env_file:
      - .env.bot1
    ports:
      - "5433:5432"
    volumes:
      - db1_data:/var/lib/postgresql/data
    restart: unless-stopped

  # База данных для второго бота
  db2:
    image: postgres:15-alpine
    container_name: poster_db2
    env_file:
      - .env.bot2
    ports:
      - "5434:5432"
    volumes:
      - db2_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Первый бот
  bot1:
    build: ./bot
    container_name: poster_bot1
    env_file:
      - .env.bot1
    depends_on:
      - db1
    restart: always

  # Второй бот
  bot2:
    build: ./bot
    container_name: poster_bot2
    env_file:
      - .env.bot2
    depends_on:
      - db2
    restart: always

volumes:
  db1_data:
  db2_data:
